[tool.poetry]
name = "telegram-integration"
version = "0.0.1"
description = "telegram integration with uagents"
authors = ["Alexander Ekzarov"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
uagents = "*"
python-telegram-bot = "^13.0"